export const units = [
  {
    code: 'VGO-014',
    name: 'Vigo Centro',
    city: 'Vigo',
    owner: 'Martinez Family',
    segment: 'Costa alta ocupacion',
    cups: 'ES0021000009347621TR',
    occupancy: 78,
    totalKwh: 428,
    outsideKwh: 42,
    cost: 87.4,
    status: 'Critica',
    reading: '19:10',
    pms: 'Guesty',
    tariff: '2.0TD · P1 0,20 / P2 0,12 / P3 0,08',
  },
  {
    code: 'COR-007',
    name: 'A Coruna Marina',
    city: 'A Coruna',
    owner: 'Lopez Gestion',
    segment: 'Propietarios premium',
    cups: 'ES0022000001187309YA',
    occupancy: 71,
    totalKwh: 386,
    outsideKwh: 21,
    cost: 64.9,
    status: 'Potencia',
    reading: '18:55',
    pms: 'Avantio',
    tariff: '2.0TD · P2 contratada 4,6 kW',
  },
  {
    code: 'SJO-021',
    name: 'Sanxenxo Playa',
    city: 'Sanxenxo',
    owner: 'Costa Rentals',
    segment: 'Costa alta ocupacion',
    cups: 'ES0031400008274510VX',
    occupancy: 84,
    totalKwh: 319,
    outsideKwh: 33,
    cost: 72.1,
    status: 'Regla',
    reading: '17:42',
    pms: 'Smoobu',
    tariff: '2.0TD · termo fuera de ventana',
  },
  {
    code: 'MDR-003',
    name: 'Madrid Letras',
    city: 'Madrid',
    owner: 'Iberhome Partners',
    segment: 'Urbano corporativo',
    cups: 'ES0021000017721033KV',
    occupancy: 62,
    totalKwh: 512,
    outsideKwh: 8,
    cost: 101.2,
    status: 'Correcta',
    reading: '19:02',
    pms: 'Hostaway',
    tariff: 'Indexada · sin accion',
  },
  {
    code: 'BCN-055',
    name: 'Barcelona Eixample',
    city: 'Barcelona',
    owner: 'Costa Rentals',
    segment: 'Propietarios premium',
    cups: 'ES0031400005589034QB',
    occupancy: 89,
    totalKwh: 202,
    outsideKwh: 17,
    cost: 58.4,
    status: 'Informe',
    reading: 'hace 27 h',
    pms: 'Rentals United',
    tariff: 'Factura pendiente de validar',
  },
]

export const actions = [
  {
    id: 'ACT-118',
    unit: 'VGO-014',
    type: 'Fuera de reserva',
    priority: 'Alta',
    title: 'Consumo 4,2 kWh tras checkout sin reserva activa',
    evidence: 'checkout 11:00 · consumo estable 13:10-16:40 · coste estimado 0,71 EUR',
    impact: 52,
    approval: 'Apagar termo y notificar a operaciones',
  },
  {
    id: 'ACT-119',
    unit: 'COR-007',
    type: 'Tarifa/Potencia',
    priority: 'Media',
    title: 'P2 sobredimensionada: 4,6 kW contratados',
    evidence: 'pico mensual P2 2,8 kW · recomendacion prudente 3,3 kW',
    impact: 138,
    approval: 'Preparar cambio con comercializadora',
  },
  {
    id: 'ACT-120',
    unit: 'SJO-021',
    type: 'Regla',
    priority: 'Alta',
    title: 'Regla post-checkout no ejecuto termo',
    evidence: 'salida 10:30 · termo activo hasta 12:06 · Shelly Pro 4PM online',
    impact: 74,
    approval: 'Reintentar automatizacion y dejar aviso',
  },
  {
    id: 'ACT-121',
    unit: 'BCN-055',
    type: 'Informe',
    priority: 'Baja',
    title: 'Resumen propietario listo para Costa Rentals',
    evidence: '201 kWh estancia · 17 kWh fuera reserva · 58,40 EUR trazados',
    impact: 58,
    approval: 'Validar informe mensual',
  },
]

export const dailyLoad = [42, 48, 51, 63, 58, 76, 71, 52, 38, 44, 67, 73, 69, 59, 47, 56, 61, 75, 82, 64, 55, 49, 62, 58]

export const tariffBands = [
  { label: 'P1 punta', price: '0,20 EUR/kWh', kwh: 612, color: 'var(--color-crimson)' },
  { label: 'P2 llano', price: '0,12 EUR/kWh', kwh: 784, color: 'var(--color-amber)' },
  { label: 'P3 valle', price: '0,08 EUR/kWh', kwh: 451, color: 'var(--color-blue)' },
]
